# -*- coding: utf-8 -*-
"""Scraping.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12qAQNDhQYfQTrMub-EoiWwNhb5IhdBBg
"""

import requests

def test_website_scrapability(url):
    try:
        response = requests.get(url)
        if response.status_code == 200:
            return "The website is accessible and potentially scrapable."
        else:
            return f"Request returned a status code of {response.status_code}. Scraping might be challenging."
    except requests.RequestException as e:
        return f"An error occurred: {e}"


test_url = 'https://ambuda.org/texts/shivopanishat/1'
result = test_website_scrapability(test_url)
print(result)

from google.colab import drive
drive.mount('/content/drive')

import requests
from bs4 import BeautifulSoup
import re
import json
import decimal

def scrape_sanskrit_words(url):
    try:
        response = requests.get(url)
        response.raise_for_status()
        soup = BeautifulSoup(response.content, 'html.parser')
        sanskrit_words = re.findall(r'[\u0900-\u097F]+', soup.get_text())
        return sanskrit_words
    except requests.RequestException as e:
        return f"An error occurred: {e}"

def scrape_entire_site(base_url):
    urls_to_scrape = []

    i = decimal.Decimal('7.1')  # Initialize i as a decimal.Decimal


    num_iterations = 90

    for _ in range(num_iterations):
        urls_to_scrape.append(base_url + str(i))
        i += decimal.Decimal('0.01')

    print(urls_to_scrape)
    all_words = {}

    for url in urls_to_scrape:
        words = scrape_sanskrit_words(url)
        if isinstance(words, list):
            all_words[url] = words

    return all_words

def save_to_json(data, filename):
    with open(filename, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=4)


base_url = 'https://ambuda.org/texts/ramayanam/'
scraped_data = scrape_entire_site(base_url)
save_to_json(scraped_data, '/content/drive/My Drive/Tensoic/Sanskrit/ramayanam_7.json')